# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: connection-opt
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: frontend
labextension_name: connection-opt
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: jupyterlab-connectionloss_opt
repository: ''
test: true
viewer_name: ''

